name: DataWarehouse
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - blas=1.0
  - boto3=1.9.111
  - botocore=1.12.112
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - cryptography=2.6.1
  - docutils=0.14
  - idna=2.8
  - intel-openmp=2019.3
  - jmespath=0.9.4
  - krb5=1.16.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpq=11.2
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.1.1b
  - pandas=0.24.2
  - pip=19.0.3
  - psycopg2=2.7.6.1
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=7.0
  - s3transfer=0.2.0
  - setuptools=41.0.0
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - urllib3=1.24.2
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11

